### PR TITLE
fix: fix that loading element is not render

### PR DESCRIPTION
**Pull request by daybrush**
## Issue

#365

### CODE REVIEW

**Comment by WoodNeck** [comment]
Is this well tested?

**Comment by daybrush** [comment]
Perhaps all users using loading with that code have gotten an error.

The changed code is the same as react, so I think there will be no problem.

**Review by mixed — COMMENTED** [review]
Can't you make test code?

**Comment by daybrush** [comment]
@mixed 

There is no test code preparation for the framework.

**Comment by mixed** [comment]
@daybrush 
Why is there no test code in the frameworks?

**Review by WoodNeck — APPROVED** [review]
LGTM

**Review by mixed — APPROVED** [review]
Let's discuss testcode in another issue.

**Pull request merged**
