### PR TITLE
fix: some minor Typos 

### PR DESCRIPTION
**Pull request by kode15333**
## Details
Found some typos

### CODE REVIEW

**Review by daybrush — APPROVED** [review]
Thank you for writing your PR. :)

**Review by mixed — APPROVED** [review]
Thank you for your first PR!

**Review by WoodNeck — APPROVED** [review]

**Comment by daybrush** [comment]
@kode15333 

Can you check the CLA?

**Comment by kode15333** [comment]
Sorry I  signed the CLA.

**Comment by daybrush** [comment]
@kode15333 

Thank you :)

**Pull request merged**
