### PR TITLE
fix(ngx-infinitegrid): re-arrange peer deps and call `next` on the destroy subject

### PR DESCRIPTION
**Pull request by arturovt**
I've removed e2e folder since it's unnecessary and updated peer dependencies to match all Angular versions greater than 11. I've removed view childs (like `wrapperRef`) since there're no such elements in the template.

### CODE REVIEW

**Review by daybrush — APPROVED** [review]
LGTM

**Review by WoodNeck — APPROVED** [review]
LGTM, thanks for the contribution! 🙌

**Review by malangfox — APPROVED** [review]
LGTM

**Comment by mixed** [comment]
@naver/egjs-dev 
Is there a reason why you can't merge?

**Pull request merged**
